Content
hvk5388/My-Personal-Website pull request #12
Opened 2020-05-16 15:46 UTC by hvk5388

includes the content description

2020-05-16 16:47 UTC, mjkern requested changes
Nice work Hannah, I made some suggestions but ultimately it is your website so need to address them.

This pr should not contain your html though, please make sure it is saved on another branch and then remove it.

2020-05-16 16:47 UTC, mjkern commented on description.md
> +As the founding treasurer of UXPA, Penn State Chapter, I have put in a lot of work to get the club started. UXPA strives to give UX students oportunities to gain expreience outside of the classroom.
The first two sound pretty good, but the last one does not quite measure up. I would not say anything about projects if you have not done any, but I would replace "put in a lot of work" with a list of your specific responsiblities or things you have done. Maybe consider flipping the first two sentances.

2020-05-16 16:47 UTC, mjkern commented on description.md
> +Clinique Virtual Reality is a way to experience personalized cosmetic advice from any location, at any time. It allows the user to scan their face, view the problem areas, and recommends products and
Nice work on the first two. My only question is what you actually created/delivered. Did you build full applications? Or just wireframes? Did you user test? Did you collaborate or work individually?

2020-05-18 17:47 UTC, mjkern commented
@hvk5388 Have you addressed these concerns yet?

2020-05-18 18:53 UTC, hvk5388 commented
yes i pushed the changes

2020-05-18 19:26 UTC, mjkern requested changes
Thanks for updating those. I'd still love to hear Mom's thoughts here, but I made my last comment below.

2020-05-18 19:26 UTC, mjkern commented on description.md
> + UXPA strives to give UX students oportunities to gain expreience outside of the classroom.As the founding treasurer of UXPA, Penn State Chapter, I have put in a lot of work to get the club started.
```suggestion
 UXPA strives to give UX students oportunities to gain expreience outside of the classroom. As the founding treasurer of UXPA, Penn State Chapter, I have put in a lot of work to get the club started. Leading meetings, recruiting members, and working to become a recognized club are some of my tasks. We haven't currently finished any projects, but we are well on our way.
```

2020-05-19 16:22 UTC, mjkern approved these changes
Nice work!

2020-05-19 16:23 UTC, merged