html
hvk5388/My-Personal-Website pull request #14
Opened 2020-05-18 15:45 UTC by hvk5388

2020-05-18 18:05 UTC, mjkern requested changes
Okay, a few things still:
- this file should be named `index.html` - did you read the issue?
- Can you include the images that you plan to use? I would add them to images folder and then link them via relative paths.

2020-05-18 18:05 UTC, mjkern commented on website_outline.html
> +
You probably want your name here, right?

2020-05-18 18:05 UTC, mjkern commented on website_outline.html
> +        <title>hannah kern</title>
You sure you want this lowercase?

2020-05-18 18:05 UTC, mjkern commented on website_outline.html
> +        LinkedIn icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon
They usually specify exactly what text you must include to use an icon - is this what they said? Do you need the creative commons lisence?

2020-05-18 18:05 UTC, mjkern commented on website_outline.html
> +        resume
This should link to your resume, right?

2020-05-19 16:56 UTC, mjkern requested changes
Better. Still a few notes below

2020-05-19 16:56 UTC, mjkern commented on index.html
> +    <img src = "https://photos.google.com/photo/AF1QipNYwca5fK7wrKjU4tJbM6ZT5NnxRMlUzUSdTZFV">
These images don't work for me... Also, you should include them in your repo and use a relative path. I would not depend on google for these.

2020-05-19 16:56 UTC, mjkern commented on index.html
> +        LinkedIn icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon
I don't see the icons that these refer to...

2020-05-19 16:56 UTC, mjkern commented on index.html
> +        </a>
This does not work. I think you should double check the syntax.

2020-05-19 16:56 UTC, mjkern commented on website_outline.html
> +        LinkedIn icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon
@hvk5388 You never addressed this. Please at least respond to the comment...

2020-05-19 16:56 UTC, mjkern commented on website_outline.html
> +<html>
This file should be deleted altogether now that you have one named `index.html`.

2020-05-20 15:40 UTC, mjkern requested changes
Nice work Hannah! Only a few minor problems

2020-05-20 15:40 UTC, mjkern commented on index.html
> +        <a href="https://drive.google.com/file/d/1VJn_JMpBiWub_GVBn46kDP1N0Syk42X8/view?usp=sharing">resume</a>
I don't have permission to follow this link

2020-05-20 15:40 UTC, mjkern commented on index.html
> +    <img src = "email (1).svg">
This file should be named better

2020-05-20 15:40 UTC, mjkern commented on index.html
> +    <img src = "email (1).svg">
actually, all three icons probably should.

And please place all of your images or icons in an folder labeled `images` or `assests` or something.

2020-05-20 17:04 UTC, mjkern approved these changes
looks good @hvk5388 

I'm a little surprised that you don't want your resume to open in another tab, but if this is operating how you like it then go ahead and merge :)

2020-05-20 17:12 UTC, mjkern commented
@hvk5388 There are no changes since my last review. Did you push?

Also, I am noticing that you never addessed my comments about attribution... can you please do that?

2020-05-20 18:25 UTC, hvk5388 commented
The attribution is correct

2020-05-20 19:01 UTC, mjkern commented
Okay, looks like I just mised your changes before. Sorry about that. And glad the attribution is right :)

2020-05-20 19:02 UTC, merged